import { expect, test } from '@playwright/test'

const run = process.env.WORKFORCE_E2E_RUN

test('creates specialist, saves hours and additional day, then reopens them', async ({ page }, testInfo) => {
  test.skip(!run, 'Use bash bin/test-workforce-e2e to provision isolated disposable tenants.')
  const device = testInfo.project.name.startsWith('mobile') ? 'mobile' : 'desktop'
  const pageErrors: string[] = []
  page.on('pageerror', (e) => pageErrors.push(e.message))
  await page.goto('/specialists')
  await page.getByLabel('Email', { exact: true }).fill(`workforce-e2e-${run}-${device}@example.test`)
  await page.getByLabel('Пароль', { exact: true }).fill('Workforce-E2E-test-only')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Специалисты', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Специалист', exact: true }).click()
  await page.getByLabel('Имя специалиста').fill('Юлия Иванова')
  await page.getByLabel('Специализация', { exact: true }).fill('Логопед')
  await page.getByLabel('Это мой профиль специалиста').check()
  await page.getByRole('button', { name: 'Сохранить специалиста' }).click()
  await expect(page.getByRole('heading', { name: 'Юлия Иванова' })).toBeVisible()
  const profileUrl = page.url()
  await page.getByRole('link', { name: 'Изменить рабочие часы' }).click()
  await page.getByRole('switch', { name: 'Понедельник', exact: true }).click()
  await page.getByRole('group', { name: 'Понедельник', exact: true }).getByRole('button', { name: 'Добавить обед' }).click()
  await page.getByRole('button', { name: 'Применить к ПН–ПТ' }).click()
  await page.getByLabel('Вторник, обед: начало', { exact: true }).fill('13:30')
  await page.getByLabel('Вторник, обед: окончание', { exact: true }).fill('14:30')
  await page.getByRole('button', { name: 'Удалить обед: Среда', exact: true }).click()
  await page.getByLabel('Среда, рабочее время: начало', { exact: true }).fill('10:00')
  await page.getByRole('button', { name: 'Сохранить часы' }).click()
  await expect(page).toHaveURL(profileUrl)
  await page.reload()
  await expect(page.getByText('Обед 13:30–14:30', { exact: true })).toBeVisible()
  await expect(page.getByText('СР · 10:00–18:00', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Добавить рабочий день', exact: true }).click()
  await page.getByLabel('Дата', { exact: true }).fill('2026-09-12')
  await page.getByLabel('Рабочее время: начало', { exact: true }).fill('10:00')
  await page.getByLabel('Рабочее время: окончание', { exact: true }).fill('15:00')
  await page.getByRole('button', { name: 'Сохранить день' }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.reload()
  await expect(page.getByText('Дополнительный рабочий день · 10:00–15:00')).toBeVisible()
  await page.getByRole('button', { name: 'Редактировать специалиста' }).click()
  await page.getByLabel('Имя специалиста').fill('Юлия Петрова')
  await page.getByRole('button', { name: 'Сохранить специалиста' }).click()
  await expect(page.getByRole('heading', { name: 'Юлия Петрова' })).toBeVisible()
  await page.getByRole('link', { name: 'Назад', exact: true }).click()
  await page.getByLabel('Поиск специалиста').fill('Юлия Петрова')
  await page.getByRole('link', { name: /Юлия Петрова/ }).click()
  await expect(page).toHaveURL(profileUrl)
  await page.goto('/my-schedule')
  await expect(page).toHaveURL(`${profileUrl}/hours`)
  await expect(page.getByRole('switch', { name: 'Суббота', exact: true })).toHaveAttribute('aria-checked', 'false')
  await expect(page.getByLabel('Среда, рабочее время: начало', { exact: true })).toHaveValue('10:00')
  expect(pageErrors).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
